name: Deploy .NET App to IIS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: ⬇️ Checkout Code
      uses: actions/checkout@v3

    - name: ⚙️ Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 🛠️ Restore Dependencies
      run: dotnet restore

    - name: 🏗️ Build Project
      run: dotnet build --configuration Release

    - name: 🚀 Publish to IIS folder directly
      run: |
        dotnet publish -c Release -o "C:\Users\kanwa\OneDrive\Desktop\LearningAndPrepration\ReactFullstackPrep\backend\ComplianceApi\ComplianceApi\bin\Release\net8.0\publish"
